/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    role: ProfileRole;
    email: string;
    verificationStatus: VerificationStatus;
    contactDetails: ContactDetails;
}
export interface SuccessResponse {
    restGapWarning?: RestGapWarning;
    booking: Booking;
    simultaneousEvents: Array<SimultaneousEventWarning>;
}
export interface SimultaneousEventWarning {
    startTime: string;
    clubName: string;
    eventDescription: string;
    endTime: string;
    venue: string;
    expectedAudience: bigint;
    contactDetails: ContactDetails;
}
export interface RestGapWarning {
    message: string;
    conflictType: string;
}
export interface ValidationWarning {
    restGapWarning?: RestGapWarning;
    simultaneousEventWarnings: Array<SimultaneousEventWarning>;
}
export interface Notification {
    id: bigint;
    title: string;
    content: string;
    isRead: boolean;
    timestamp: bigint;
}
export interface Booking {
    id: bigint;
    startTime: string;
    status: BookingStatus;
    clubName: string;
    eventDescription: string;
    clubContact: ContactDetails;
    endTime: string;
    venue: string;
    date: string;
    expectedAudience: bigint;
}
export interface ContactDetails {
    name: string;
    phone: string;
}
export type BookingResponse = {
    __kind__: "conflict";
    conflict: ConflictResponse;
} | {
    __kind__: "success";
    success: SuccessResponse;
};
export interface ConflictResponse {
    conflictingBooking: Booking;
    message: string;
}
export interface VerificationRequest {
    status: VerificationStatus;
    principal: Principal;
    email: string;
    contactDetails: ContactDetails;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ProfileRole {
    studentCoordinator = "studentCoordinator",
    faculty = "faculty",
    student = "student"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VerificationStatus {
    verified = "verified",
    pending = "pending",
    unverified = "unverified"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveVerificationRequest(studentCoordinatorPrincipal: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelBooking(bookingId: bigint): Promise<void>;
    cancelBookings(bookingIds: Array<bigint>): Promise<void>;
    getAllUpcomingBookings(currentDate: string): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPendingVerificationRequests(): Promise<Array<VerificationRequest>>;
    getTodaysSchedule(today: string): Promise<Array<Booking>>;
    getUpcomingUserBookings(currentDate: string): Promise<Array<Booking>>;
    getUserBookings(): Promise<Array<Booking>>;
    getUserNotifications(): Promise<Array<Notification>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isUserRegistered(): Promise<boolean>;
    isVerifiedForBookings(): Promise<boolean>;
    previewBooking(clubName: string, eventDescription: string, clubContact: ContactDetails, venue: string, date: string, startTime: string, endTime: string, expectedAudience: bigint): Promise<ValidationWarning | null>;
    registerFacultyProfile(target: Principal, email: string, contactDetails: ContactDetails): Promise<void>;
    registerProfile(email: string, role: ProfileRole, contactDetails: ContactDetails): Promise<void>;
    rejectVerificationRequest(studentCoordinatorPrincipal: Principal): Promise<void>;
    requestBooking(clubName: string, eventDescription: string, clubContact: ContactDetails, venue: string, date: string, startTime: string, endTime: string, expectedAudience: bigint, confirmRestGap: boolean): Promise<BookingResponse>;
    resolveCoordinatorVerificationNotifications(_coordinatorPrincipal: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Booking as _Booking, BookingResponse as _BookingResponse, BookingStatus as _BookingStatus, ConflictResponse as _ConflictResponse, ContactDetails as _ContactDetails, ProfileRole as _ProfileRole, RestGapWarning as _RestGapWarning, SimultaneousEventWarning as _SimultaneousEventWarning, SuccessResponse as _SuccessResponse, UserProfile as _UserProfile, UserRole as _UserRole, ValidationWarning as _ValidationWarning, VerificationRequest as _VerificationRequest, VerificationStatus as _VerificationStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveVerificationRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveVerificationRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveVerificationRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async cancelBookings(arg0: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBookings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBookings(arg0);
            return result;
        }
    }
    async getAllUpcomingBookings(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUpcomingBookings(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUpcomingBookings(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingVerificationRequests(): Promise<Array<VerificationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingVerificationRequests();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingVerificationRequests();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaysSchedule(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysSchedule(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysSchedule(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingUserBookings(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingUserBookings(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingUserBookings(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBookings();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBookings();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNotifications();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUserRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserRegistered();
            return result;
        }
    }
    async isVerifiedForBookings(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isVerifiedForBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isVerifiedForBookings();
            return result;
        }
    }
    async previewBooking(arg0: string, arg1: string, arg2: ContactDetails, arg3: string, arg4: string, arg5: string, arg6: string, arg7: bigint): Promise<ValidationWarning | null> {
        if (this.processError) {
            try {
                const result = await this.actor.previewBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.previewBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerFacultyProfile(arg0: Principal, arg1: string, arg2: ContactDetails): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFacultyProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFacultyProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async registerProfile(arg0: string, arg1: ProfileRole, arg2: ContactDetails): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile(arg0, to_candid_ProfileRole_n24(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile(arg0, to_candid_ProfileRole_n24(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async rejectVerificationRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectVerificationRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectVerificationRequest(arg0);
            return result;
        }
    }
    async requestBooking(arg0: string, arg1: string, arg2: ContactDetails, arg3: string, arg4: string, arg5: string, arg6: string, arg7: bigint, arg8: boolean): Promise<BookingResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.requestBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_BookingResponse_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_BookingResponse_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async resolveCoordinatorVerificationNotifications(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveCoordinatorVerificationNotifications(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveCoordinatorVerificationNotifications(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BookingResponse_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingResponse): BookingResponse {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ConflictResponse_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConflictResponse): ConflictResponse {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileRole): ProfileRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SuccessResponse_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SuccessResponse): SuccessResponse {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ValidationWarning_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ValidationWarning): ValidationWarning {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationRequest_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationRequest): VerificationRequest {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ValidationWarning]): ValidationWarning | null {
    return value.length === 0 ? null : from_candid_ValidationWarning_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestGapWarning]): RestGapWarning | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _ProfileRole;
    email: string;
    verificationStatus: _VerificationStatus;
    contactDetails: _ContactDetails;
}): {
    role: ProfileRole;
    email: string;
    verificationStatus: VerificationStatus;
    contactDetails: ContactDetails;
} {
    return {
        role: from_candid_ProfileRole_n11(_uploadFile, _downloadFile, value.role),
        email: value.email,
        verificationStatus: from_candid_VerificationStatus_n13(_uploadFile, _downloadFile, value.verificationStatus),
        contactDetails: value.contactDetails
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _VerificationStatus;
    principal: Principal;
    email: string;
    contactDetails: _ContactDetails;
}): {
    status: VerificationStatus;
    principal: Principal;
    email: string;
    contactDetails: ContactDetails;
} {
    return {
        status: from_candid_VerificationStatus_n13(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        email: value.email,
        contactDetails: value.contactDetails
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    restGapWarning: [] | [_RestGapWarning];
    simultaneousEventWarnings: Array<_SimultaneousEventWarning>;
}): {
    restGapWarning?: RestGapWarning;
    simultaneousEventWarnings: Array<SimultaneousEventWarning>;
} {
    return {
        restGapWarning: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.restGapWarning)),
        simultaneousEventWarnings: value.simultaneousEventWarnings
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    conflictingBooking: _Booking;
    message: string;
}): {
    conflictingBooking: Booking;
    message: string;
} {
    return {
        conflictingBooking: from_candid_Booking_n4(_uploadFile, _downloadFile, value.conflictingBooking),
        message: value.message
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    restGapWarning: [] | [_RestGapWarning];
    booking: _Booking;
    simultaneousEvents: Array<_SimultaneousEventWarning>;
}): {
    restGapWarning?: RestGapWarning;
    booking: Booking;
    simultaneousEvents: Array<SimultaneousEventWarning>;
} {
    return {
        restGapWarning: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.restGapWarning)),
        booking: from_candid_Booking_n4(_uploadFile, _downloadFile, value.booking),
        simultaneousEvents: value.simultaneousEvents
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: string;
    status: _BookingStatus;
    clubName: string;
    eventDescription: string;
    clubContact: _ContactDetails;
    endTime: string;
    venue: string;
    date: string;
    expectedAudience: bigint;
}): {
    id: bigint;
    startTime: string;
    status: BookingStatus;
    clubName: string;
    eventDescription: string;
    clubContact: ContactDetails;
    endTime: string;
    venue: string;
    date: string;
    expectedAudience: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_BookingStatus_n6(_uploadFile, _downloadFile, value.status),
        clubName: value.clubName,
        eventDescription: value.eventDescription,
        clubContact: value.clubContact,
        endTime: value.endTime,
        venue: value.venue,
        date: value.date,
        expectedAudience: value.expectedAudience
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentCoordinator: null;
} | {
    faculty: null;
} | {
    student: null;
}): ProfileRole {
    return "studentCoordinator" in value ? ProfileRole.studentCoordinator : "faculty" in value ? ProfileRole.faculty : "student" in value ? ProfileRole.student : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    unverified: null;
}): VerificationStatus {
    return "verified" in value ? VerificationStatus.verified : "pending" in value ? VerificationStatus.pending : "unverified" in value ? VerificationStatus.unverified : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    conflict: _ConflictResponse;
} | {
    success: _SuccessResponse;
}): {
    __kind__: "conflict";
    conflict: ConflictResponse;
} | {
    __kind__: "success";
    success: SuccessResponse;
} {
    return "conflict" in value ? {
        __kind__: "conflict",
        conflict: from_candid_ConflictResponse_n28(_uploadFile, _downloadFile, value.conflict)
    } : "success" in value ? {
        __kind__: "success",
        success: from_candid_SuccessResponse_n30(_uploadFile, _downloadFile, value.success)
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "approved" in value ? BookingStatus.approved : "rejected" in value ? BookingStatus.rejected : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VerificationRequest>): Array<VerificationRequest> {
    return value.map((x)=>from_candid_VerificationRequest_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ProfileRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileRole): _ProfileRole {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VerificationStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): _VerificationStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: ProfileRole;
    email: string;
    verificationStatus: VerificationStatus;
    contactDetails: ContactDetails;
}): {
    role: _ProfileRole;
    email: string;
    verificationStatus: _VerificationStatus;
    contactDetails: _ContactDetails;
} {
    return {
        role: to_candid_ProfileRole_n24(_uploadFile, _downloadFile, value.role),
        email: value.email,
        verificationStatus: to_candid_VerificationStatus_n34(_uploadFile, _downloadFile, value.verificationStatus),
        contactDetails: value.contactDetails
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileRole): {
    studentCoordinator: null;
} | {
    faculty: null;
} | {
    student: null;
} {
    return value == ProfileRole.studentCoordinator ? {
        studentCoordinator: null
    } : value == ProfileRole.faculty ? {
        faculty: null
    } : value == ProfileRole.student ? {
        student: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): {
    verified: null;
} | {
    pending: null;
} | {
    unverified: null;
} {
    return value == VerificationStatus.verified ? {
        verified: null
    } : value == VerificationStatus.pending ? {
        pending: null
    } : value == VerificationStatus.unverified ? {
        unverified: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
