/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ContactDetails = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'status' : BookingStatus,
  'clubName' : IDL.Text,
  'eventDescription' : IDL.Text,
  'clubContact' : ContactDetails,
  'endTime' : IDL.Text,
  'venue' : IDL.Text,
  'date' : IDL.Text,
  'expectedAudience' : IDL.Nat,
});
export const ProfileRole = IDL.Variant({
  'studentCoordinator' : IDL.Null,
  'faculty' : IDL.Null,
  'student' : IDL.Null,
});
export const VerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'unverified' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'role' : ProfileRole,
  'email' : IDL.Text,
  'verificationStatus' : VerificationStatus,
  'contactDetails' : ContactDetails,
});
export const VerificationRequest = IDL.Record({
  'status' : VerificationStatus,
  'principal' : IDL.Principal,
  'email' : IDL.Text,
  'contactDetails' : ContactDetails,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'timestamp' : IDL.Int,
});
export const RestGapWarning = IDL.Record({
  'message' : IDL.Text,
  'conflictType' : IDL.Text,
});
export const SimultaneousEventWarning = IDL.Record({
  'startTime' : IDL.Text,
  'clubName' : IDL.Text,
  'eventDescription' : IDL.Text,
  'endTime' : IDL.Text,
  'venue' : IDL.Text,
  'expectedAudience' : IDL.Nat,
  'contactDetails' : ContactDetails,
});
export const ValidationWarning = IDL.Record({
  'restGapWarning' : IDL.Opt(RestGapWarning),
  'simultaneousEventWarnings' : IDL.Vec(SimultaneousEventWarning),
});
export const ConflictResponse = IDL.Record({
  'conflictingBooking' : Booking,
  'message' : IDL.Text,
});
export const SuccessResponse = IDL.Record({
  'restGapWarning' : IDL.Opt(RestGapWarning),
  'booking' : Booking,
  'simultaneousEvents' : IDL.Vec(SimultaneousEventWarning),
});
export const BookingResponse = IDL.Variant({
  'conflict' : ConflictResponse,
  'success' : SuccessResponse,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveVerificationRequest' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'cancelBookings' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'getAllUpcomingBookings' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingVerificationRequests' : IDL.Func(
      [],
      [IDL.Vec(VerificationRequest)],
      ['query'],
    ),
  'getTodaysSchedule' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getUpcomingUserBookings' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'isVerifiedForBookings' : IDL.Func([], [IDL.Bool], ['query']),
  'previewBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ContactDetails,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Opt(ValidationWarning)],
      ['query'],
    ),
  'registerFacultyProfile' : IDL.Func(
      [IDL.Principal, IDL.Text, ContactDetails],
      [],
      [],
    ),
  'registerProfile' : IDL.Func([IDL.Text, ProfileRole, ContactDetails], [], []),
  'rejectVerificationRequest' : IDL.Func([IDL.Principal], [], []),
  'requestBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ContactDetails,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
      ],
      [BookingResponse],
      [],
    ),
  'resolveCoordinatorVerificationNotifications' : IDL.Func(
      [IDL.Principal],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ContactDetails = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'status' : BookingStatus,
    'clubName' : IDL.Text,
    'eventDescription' : IDL.Text,
    'clubContact' : ContactDetails,
    'endTime' : IDL.Text,
    'venue' : IDL.Text,
    'date' : IDL.Text,
    'expectedAudience' : IDL.Nat,
  });
  const ProfileRole = IDL.Variant({
    'studentCoordinator' : IDL.Null,
    'faculty' : IDL.Null,
    'student' : IDL.Null,
  });
  const VerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'unverified' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'role' : ProfileRole,
    'email' : IDL.Text,
    'verificationStatus' : VerificationStatus,
    'contactDetails' : ContactDetails,
  });
  const VerificationRequest = IDL.Record({
    'status' : VerificationStatus,
    'principal' : IDL.Principal,
    'email' : IDL.Text,
    'contactDetails' : ContactDetails,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  const RestGapWarning = IDL.Record({
    'message' : IDL.Text,
    'conflictType' : IDL.Text,
  });
  const SimultaneousEventWarning = IDL.Record({
    'startTime' : IDL.Text,
    'clubName' : IDL.Text,
    'eventDescription' : IDL.Text,
    'endTime' : IDL.Text,
    'venue' : IDL.Text,
    'expectedAudience' : IDL.Nat,
    'contactDetails' : ContactDetails,
  });
  const ValidationWarning = IDL.Record({
    'restGapWarning' : IDL.Opt(RestGapWarning),
    'simultaneousEventWarnings' : IDL.Vec(SimultaneousEventWarning),
  });
  const ConflictResponse = IDL.Record({
    'conflictingBooking' : Booking,
    'message' : IDL.Text,
  });
  const SuccessResponse = IDL.Record({
    'restGapWarning' : IDL.Opt(RestGapWarning),
    'booking' : Booking,
    'simultaneousEvents' : IDL.Vec(SimultaneousEventWarning),
  });
  const BookingResponse = IDL.Variant({
    'conflict' : ConflictResponse,
    'success' : SuccessResponse,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveVerificationRequest' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'cancelBookings' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'getAllUpcomingBookings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingVerificationRequests' : IDL.Func(
        [],
        [IDL.Vec(VerificationRequest)],
        ['query'],
      ),
    'getTodaysSchedule' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getUpcomingUserBookings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'isVerifiedForBookings' : IDL.Func([], [IDL.Bool], ['query']),
    'previewBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ContactDetails,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Opt(ValidationWarning)],
        ['query'],
      ),
    'registerFacultyProfile' : IDL.Func(
        [IDL.Principal, IDL.Text, ContactDetails],
        [],
        [],
      ),
    'registerProfile' : IDL.Func(
        [IDL.Text, ProfileRole, ContactDetails],
        [],
        [],
      ),
    'rejectVerificationRequest' : IDL.Func([IDL.Principal], [], []),
    'requestBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ContactDetails,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
        ],
        [BookingResponse],
        [],
      ),
    'resolveCoordinatorVerificationNotifications' : IDL.Func(
        [IDL.Principal],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };