/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'startTime' : string,
  'status' : BookingStatus,
  'clubName' : string,
  'eventDescription' : string,
  'clubContact' : ContactDetails,
  'endTime' : string,
  'venue' : string,
  'date' : string,
  'expectedAudience' : bigint,
}
export type BookingResponse = { 'conflict' : ConflictResponse } |
  { 'success' : SuccessResponse };
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ConflictResponse {
  'conflictingBooking' : Booking,
  'message' : string,
}
export interface ContactDetails { 'name' : string, 'phone' : string }
export interface Notification {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isRead' : boolean,
  'timestamp' : bigint,
}
export type ProfileRole = { 'studentCoordinator' : null } |
  { 'faculty' : null } |
  { 'student' : null };
export interface RestGapWarning { 'message' : string, 'conflictType' : string }
export interface SimultaneousEventWarning {
  'startTime' : string,
  'clubName' : string,
  'eventDescription' : string,
  'endTime' : string,
  'venue' : string,
  'expectedAudience' : bigint,
  'contactDetails' : ContactDetails,
}
export interface SuccessResponse {
  'restGapWarning' : [] | [RestGapWarning],
  'booking' : Booking,
  'simultaneousEvents' : Array<SimultaneousEventWarning>,
}
export interface UserProfile {
  'role' : ProfileRole,
  'email' : string,
  'verificationStatus' : VerificationStatus,
  'contactDetails' : ContactDetails,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValidationWarning {
  'restGapWarning' : [] | [RestGapWarning],
  'simultaneousEventWarnings' : Array<SimultaneousEventWarning>,
}
export interface VerificationRequest {
  'status' : VerificationStatus,
  'principal' : Principal,
  'email' : string,
  'contactDetails' : ContactDetails,
}
export type VerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'unverified' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveVerificationRequest' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'cancelBookings' : ActorMethod<[Array<bigint>], undefined>,
  'getAllUpcomingBookings' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingVerificationRequests' : ActorMethod<
    [],
    Array<VerificationRequest>
  >,
  'getTodaysSchedule' : ActorMethod<[string], Array<Booking>>,
  'getUpcomingUserBookings' : ActorMethod<[string], Array<Booking>>,
  'getUserBookings' : ActorMethod<[], Array<Booking>>,
  'getUserNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserRegistered' : ActorMethod<[], boolean>,
  'isVerifiedForBookings' : ActorMethod<[], boolean>,
  'previewBooking' : ActorMethod<
    [string, string, ContactDetails, string, string, string, string, bigint],
    [] | [ValidationWarning]
  >,
  'registerFacultyProfile' : ActorMethod<
    [Principal, string, ContactDetails],
    undefined
  >,
  'registerProfile' : ActorMethod<
    [string, ProfileRole, ContactDetails],
    undefined
  >,
  'rejectVerificationRequest' : ActorMethod<[Principal], undefined>,
  'requestBooking' : ActorMethod<
    [
      string,
      string,
      ContactDetails,
      string,
      string,
      string,
      string,
      bigint,
      boolean,
    ],
    BookingResponse
  >,
  'resolveCoordinatorVerificationNotifications' : ActorMethod<
    [Principal],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];